/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by .bunext/generate-routes.ts
 * Run `bun .bunext/generate-routes.ts` to regenerate
 */

import type React from "react";

// Page imports
import AboutPage from "../src/pages/about/index";
import CatchAllCatchAllSlugPage from "../src/pages/catch/all/[...slug]/index";
import CatchOptOptionalCatchAllSlugPage from "../src/pages/catch/opt/[[...slug]]/index";
import DynamicIdPage from "../src/pages/dynamic/[id]/index";
import HomePage from "../src/pages/index";

// Layout imports
import DynamicIdLayoutLayout from "../src/pages/dynamic/[id]/layout";

// Routes map: route path -> component
export const routes: Record<string, React.ComponentType> = {
  "/about/index": AboutPage,
  "/catch/all/[...slug]/index": CatchAllCatchAllSlugPage,
  "/catch/opt/[[...slug]]/index": CatchOptOptionalCatchAllSlugPage,
  "/dynamic/[id]/index": DynamicIdPage,
  "/index": HomePage,
};

// Layouts map: layout path -> component
export const layouts: Record<string, React.ComponentType<{ children: React.ReactNode }>> = {
  "/dynamic/[id]/layout": DynamicIdLayoutLayout,
};
